visitaprom:
    path:     /
    defaults: { _controller: "AppBundle:VisitaPromocion:index" }

visitaprom_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:VisitaPromocion:show" }

visitaprom_new:
    path:     /new
    defaults: { _controller: "AppBundle:VisitaPromocion:new" }

visitaprom_create:
    path:     /create
    defaults: { _controller: "AppBundle:VisitaPromocion:create" }
    methods:  POST

visitaprom_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:VisitaPromocion:edit" }

visitaprom_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:VisitaPromocion:update" }
    methods:  [POST, PUT]

visitaprom_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:VisitaPromocion:delete" }
    methods:  [POST, DELETE]
    
visitaprom_ajax_grafico:
    path:     /ajax_grafico
    defaults: { _controller: "AppBundle:VisitaPromocion:ajax" }
    condition: "request.isXmlHttpRequest()"
