visitalocalcomercial:
    path:     /
    defaults: { _controller: "AppBundle:VisitaLocalComercial:index" }

visitalocalcomercial_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:VisitaLocalComercial:show" }

visitalocalcomercial_new:
    path:     /new
    defaults: { _controller: "AppBundle:VisitaLocalComercial:new" }

visitalocalcomercial_create:
    path:     /create
    defaults: { _controller: "AppBundle:VisitaLocalComercial:create" }
    methods:  POST

visitalocalcomercial_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:VisitaLocalComercial:edit" }

visitalocalcomercial_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:VisitaLocalComercial:update" }
    methods:  [POST, PUT]

visitalocalcomercial_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:VisitaLocalComercial:delete" }
    methods:  [POST, DELETE]
