programacion:
    path:     /
    defaults: { _controller: "dromoAppLocalBundle:Programacion:index" }

programacion_show:
    path:     /{id}/show
    defaults: { _controller: "dromoAppLocalBundle:Programacion:show" }

programacion_new:
    path:     /new
    defaults: { _controller: "dromoAppLocalBundle:Programacion:new" }

programacion_create:
    path:     /create
    defaults: { _controller: "dromoAppLocalBundle:Programacion:create" }
    methods:  POST

programacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "dromoAppLocalBundle:Programacion:edit" }

programacion_update:
    path:     /{id}/update
    defaults: { _controller: "dromoAppLocalBundle:Programacion:update" }
    methods:  [POST, PUT]

programacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "dromoAppLocalBundle:Programacion:delete" }
    methods:  [POST, DELETE]
