promocion:
    path:     /
    defaults: { _controller: "dromoAppLocalBundle:Promocion:index" }

promocion_show:
    path:     /{id}/show
    defaults: { _controller: "dromoAppLocalBundle:Promocion:show" }

promocion_new:
    path:     /new
    defaults: { _controller: "dromoAppLocalBundle:Promocion:new" }

promocion_create:
    path:     /create
    defaults: { _controller: "dromoAppLocalBundle:Promocion:create" }
    methods:  POST

promocion_edit:
    path:     /{id}/edit
    defaults: { _controller: "dromoAppLocalBundle:Promocion:edit" }

promocion_update:
    path:     /{id}/update
    defaults: { _controller: "dromoAppLocalBundle:Promocion:update" }
    methods:  [POST, PUT]

promocion_delete:
    path:     /{id}/delete
    defaults: { _controller: "dromoAppLocalBundle:Promocion:delete" }
    methods:  [POST, DELETE]
