<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CobroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CobroRepository extends EntityRepository
{
    /**
     * Retorna los cobros de el local
     * 
     * @param integer $idLocal
     */
    public function getCobrosLocal($idLocal){
        $query = $this->getEntityManager()
                ->createQuery(
                        "select c.id, c.fecha, c.total
                from AppBundle:Cobro c
                where c.localComercial=:paramIdLocal
                ORDER BY c.fecha")
                ->setParameter('paramIdLocal', $idLocal);

        //echo $query->getSQL();exit;
        return $query->getResult();
    }
}
