<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends EntityRepository {

    function getComentariosDenunciados() {
        $comentarios = $this->getEntityManager()
                ->createQuery('SELECT c FROM AppBundle:Comentario c '
                        . 'LEFT JOIN c.estadoComentario e '
                        . 'WHERE e.nombre = :nombre ')
                ->setParameters(array(
                    'nombre' => 'Denunciado'))
                ->getResult();
        return $comentarios;
    }

    function getComentariosLocal($idLocal) {
        $comentarios = $this->getEntityManager()
                ->createQuery('SELECT c FROM AppBundle:Comentario c '
                        . 'LEFT JOIN c.localComercial l '
                        . 'LEFT JOIN c.estadoComentario e '
                        . 'WHERE l.id = :idLocal ')
                ->setParameters(array(
                    'idLocal' => $idLocal
                    ))
                ->getResult();
        return $comentarios;
    }

}
