<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CuponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuponRepository extends EntityRepository
{
    public function crearNuevoCupon(ProgramacionEnDia $programacionEnDia, UsuarioMovil $usuarioMovil) {
        $cupon = new Cupon();
        $cupon->setCodigo(uniqid());
        $cupon->setEstadoCupon(
                $this->getEntityManager()->getRepository('AppBundle:EstadoCupon')->findOneByNombre('porCanjear')
            );
        $cupon->setFecha(new \DateTime("now"));
        $cupon->setInicio($programacionEnDia->getInicio());
        $cupon->setVencimiento($programacionEnDia->getVencimiento());
        $cupon->setProgramacion($programacionEnDia->getProgramacion());
        $cupon->setUsuarioMovil($usuarioMovil);
        
        
        $promocion = $programacionEnDia->getProgramacion()->getPromocion();
        if($promocion->getTipoPromocion()->getNombre() == 'premio'){
            //si la promocion es a la vez un premio tego q restarle al usuario movil los puntos de esta
            $puntosPremio = $promocion->getPuntajePremio();
            $usuarioMovil->setPuntos($usuarioMovil->getPuntos() - $puntosPremio);
            $this->getEntityManager()->persist($usuarioMovil);
            $tipoCupon = $this->getEntityManager()->getRepository('AppBundle:TipoCupon')->findOneByNombre('premio');
        }else{
            $tipoCupon = $this->getEntityManager()->getRepository('AppBundle:TipoCupon')->findOneByNombre('promocion');
        }
        $cupon->setTipoCupon($tipoCupon);
        
        $this->getEntityManager()->persist($cupon);
        $this->getEntityManager()->flush();
        return $cupon;
    }
    
    /**
     * registra en la bd un cupon como canjeado actualizando su estado
     * si es una pormocion y tiene puntos. se suman esos puntos al usuarioMovil que adquirio el cupon
     * actualiza el estado de cobro del cupon a pendiente
     * @param integer $idCupon
     */
    public function canjearCupon($idCupon){
        /* @var AppBundle\Entity\Cupon $cupon */
        $cupon = $this->find($idCupon);
        if($cupon->esCuponEnfecha()){
            $repositoryEstadoCupon = $this->getEntityManager()->getRepository('AppBundle:EstadoCupon');
            $repositoryEstadoCobroCupon = $this->getEntityManager()->getRepository('AppBundle:EstadoCobroCupon');
            $estadoCanjeado = $repositoryEstadoCupon->findOneByNombre('canjeado');
            $estadoCobroPendiente = $repositoryEstadoCobroCupon->findOneByNombre('pendiente');
            $cupon->setEstadoCupon($estadoCanjeado);
            $cupon->setEstadoCobroCupon($estadoCobroPendiente);
            $this->calcPrecioCobroYPuntos($cupon);
            $this->getEntityManager()->persist($cupon);
            if(!is_null($cupon->getPuntaje()) && $cupon->getPuntaje() > 0 && $cupon->getTipoCupon()->getNombre() == 'promocion'){
                $usuarioMovil = $cupon->getUsuarioMovil();
                $usuarioMovil->setPuntos($usuarioMovil->getPuntos()+$cupon->getPuntaje());
                $this->getEntityManager()->persist($usuarioMovil);
            }
            $this->getEntityManager()->flush();
            return array('exito' => true, 'cupon' => $cupon);
        }else{
            return array('exito' => false, 'cupon' => $cupon);
        }
    }
    
    /**
     * Retorna un array con los cupones vendidos por el local
     * con el id de usuario pasado por paremetro
     * 
     * @param int $idUserLocal
     * @return array array de objetos cupon
     */
    public function getVentasLocal($idUserLocal){
        $query = $this->getEntityManager()
            ->createQuery(
                "select cup
                from AppBundle:Cupon cup
                    left join cup.estadoCupon ec
                    left join cup.programacion prog
                    left join cup.tipoCupon tc
                    left join prog.promocion prom
                    left join prom.localComercial lc
                where ec.nombre=:paramEstadoCupon
                    and lc.usuario=:paramUsuario
                    and tc.nombre=:paramTipoCupon")
            ->setParameter('paramEstadoCupon', 'canjeado')
            ->setParameter('paramUsuario', $idUserLocal)
            ->setParameter('paramTipoCupon', 'promocion');
        
        //echo $query->getSQL();exit;
        return $query->getResult();
    }
    
    public function calcPrecioCobroYPuntos(Cupon $cupon){
        $precioPromocion = $cupon->getProgramacion()->getPromocion()->getPrecio();
        $repositoryVariable = $this->getEntityManager()->getRepository('AppBundle:Variables');
        $ArrayVariables = $repositoryVariable->findAll();
        $variables = $ArrayVariables[0];
        //se calcula el precio que se le cobra al local
        $precioCobroLocal = $precioPromocion*$variables->getPorcCobroLocal();
        //se calcula la cantidad de puntos del cupon
        $puntosCupon = ($precioCobroLocal*(1-$variables->getPorcGanancia())*$variables->getValorPunto());
        $puntosCupon = round($puntosCupon, 0, PHP_ROUND_HALF_DOWN);
        $cupon->setPuntaje($puntosCupon);
        $cupon->setPrecioCobroLocal($precioCobroLocal);
        return $cupon;
    }
    
    /**
     * Recorre los cupones con estado porCanjear y que se haya pasado su vencimiento y les actualiza el estado.
     * 
     * @return array con la cantidas de cupones vencidos
     */
    public function actualizarVigenciaCupones(){
        $fechaHoy = new \DateTime('now');
        $query = $this->getEntityManager()
            ->createQuery(
                "select cup
                from AppBundle:Cupon cup
                    left join cup.estadoCupon ec
                where ec.nombre=:paramEstadoCupon
                and cup.vencimiento<=:paramFechaHoy")
            ->setParameter('paramEstadoCupon', 'porCanjear')
            ->setParameter('paramFechaHoy', $fechaHoy);
        
        $arrayCupones = $query->getResult();
        $arrayResult['cupones-vencidos']=count($arrayCupones);
        if($arrayResult['cupones-vencidos']>0){
            $entityManager = $this->getEntityManager();
            $repoEstadoCupon = $entityManager->getRepository('AppBundle:EstadoCupon');
            $estadoVencido = $repoEstadoCupon->findOneByNombre('vencido');
            foreach ($arrayCupones as $cupon) {
                $cupon->setEstadoCupon($estadoVencido);
                $entityManager->persist($cupon);
            }
            $entityManager->flush();
        }
        
        return $arrayResult;
    }
    
    public function getCuponesCobro($idCobro){
        $query = $this->getEntityManager()
            ->createQuery(
                "select cup
                from AppBundle:Cupon cup
                where cup.cobro=:paramCobro")
            ->setParameter('paramCobro', $idCobro);
        
        //echo $query->getSQL();exit;
        return $query->getResult();
    }
}
