<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocalComercialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalComercialRepository extends EntityRepository
{
    
       /**
     * @param type $array
     * @return boolean
     */ 
    public function ordenarPorDistanciaALocal($array) {
        return uasort($array, function(LocalComercial $a, LocalComercial $b) {
            return $a->compareTo($b);
        }
        );
    }
}
