<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProgramacionEnDiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramacionEnDiaRepository extends EntityRepository
{
    /**
     * @param type $array
     * @return boolean
     */ 
    public function ordenarPorDistanciaALocal(&$array) {
        return uasort($array, function(ProgramacionEnDia $a, ProgramacionEnDia $b) {
            return $a->compareTo($b);
        }
        );
    }

}
