<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromocionEnDiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromocionEnDiaRepository extends EntityRepository
{
    /**
     * @param type $array
     * @return boolean
     */
    public function ordenarPorDistanciaALocal(&$array){
        return uasort($array, 
                    function(PromocionEnDia $a, PromocionEnDia $b) {
                        return $a->compareTo($b);
                    }
                );
    }
}
