<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\DependencyInjection\Parameter;
use Doctrine\Common\Collections\Criteria;

/**
 * PromocionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromocionRepository extends EntityRepository {

    /**
     * Retorna un array con las promociones de el local pasado por id y que no esten eliminadas
     * @param integer $idLocal
     * @return array
     */
    function getPromocionesLocal($idLocal) {
        $promociones = $this->getEntityManager()
                ->createQuery('SELECT p FROM AppBundle:Promocion p '
                        . 'LEFT JOIN p.localComercial l '
                        . 'LEFT JOIN p.estadoPromocion e '
                        . 'WHERE l.id = :idLocal AND e.nombre != :nombreEstado and p.puntajePremio = 0')
                ->setParameters(array(
                    'idLocal' => $idLocal,
                    'nombreEstado' => 'eliminada'))
                ->getResult();
        return $promociones;
    }

    /**
     * Retorna un array con los premios y que no esten eliminados
     * 
     * @return array
     */
    function getPremios() {
        $promociones = $this->getEntityManager()
                ->createQuery('SELECT p FROM AppBundle:Promocion p '
                        . 'LEFT JOIN p.localComercial l '
                        . 'LEFT JOIN p.estadoPromocion e '
                        . 'LEFT JOIN p.tipoPromocion t '
                        . 'WHERE e.nombre != :nombreEstado and t.nombre= :tipoPremio')
                ->setParameters(array(
                    'nombreEstado' => 'eliminada',
                    'tipoPremio' => 'premio'))
                ->getResult();
        return $promociones;
    }

    /**
     * Retorna un array con los premios de un local y que no esten eliminados
     * 
     * @return array
     */
    function getPremiosLocal($idLocal) {
        $promociones = $this->getEntityManager()
                ->createQuery('SELECT p FROM AppBundle:Promocion p '
                        . 'LEFT JOIN p.localComercial l '
                        . 'LEFT JOIN p.estadoPromocion e '
                        . 'WHERE l.id = :idLocal AND e.nombre != :nombreEstado and p.puntajePremio!= 0')
                ->setParameters(array(
                    'idLocal' => $idLocal,
                    'nombreEstado' => 'eliminada'))
                ->getResult();
        return $promociones;
    }

    /**
     * Controla si una promocion es de tipo premio
     * Si es premio controla que el usuario que la quiere canjear tenga los puntos necesarios
     * 
     * @return boolean retorna True si el usuario tiene los puntos necesarios o no es premio 
     *  Retorna False si es premio y el usuario no tiene los puntos necesarios 
     */
    function validarPuntosUsuario(\AppBundle\Entity\Promocion $promocion, \AppBundle\Entity\UsuarioMovil $usuarioMovil){
        if ($promocion->getTipoPromocion()->getNombre() == 'premio') {
            if ($promocion->getPuntajePremio() > $usuarioMovil->getPuntos()) {
                return false;
            }
        }
        return true;
    }
}
