<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SucursalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SucursalRepository extends EntityRepository
{
    public function getListSucursalesPorDistancia($arraySucursales, $latitudUM, $longitudUM){
        //return $arraySucursales;
        foreach ($arraySucursales as $sucursal) {
            /* @var $sucursal Sucursal */
            $sucursal->calcularDistanciaAUsuarioMovil($latitudUM, $longitudUM);
        }
        
        uasort($arraySucursales, 
                function(Sucursal $a, Sucursal $b) {
                    return $a->compareTo($b);
                }
        );
        
        return $arraySucursales;
    }
}
