<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuscripcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuscripcionRepository extends EntityRepository
{
}
