<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TotalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TotalesRepository extends EntityRepository
{
    public function sumarTotales(Cobro $cobro) {
        $em = $this->getEntityManager();
        $cupones = $em->getRepository('AppBundle:Cupon')->findByCobro($cobro);
        
        $variables = $em->getRepository('AppBundle:Variables')->findAll();
        $valorPunto = $variables[0]->getValorPunto();
        
        $totales = $this->findAll();
        $sumaCobroLocales = $totales[0]->getTotalCobroLocales();
        $sumaGanancia = $totales[0]->getTotalGanancia();
        $sumaParaPremios =  $totales[0]->getTotalParaPremios();
        
        foreach ($cupones as $cupon) {
            $cobroLocalCupon = $cupon->getPrecioCobroLocal();
            $paraPremiosCupon = $cupon->getPuntaje()/$valorPunto;
            $gananciaCupon = $cobroLocalCupon-$paraPremiosCupon;
            
            $sumaCobroLocales+=$cobroLocalCupon;
            $sumaGanancia+=$gananciaCupon;
            $sumaParaPremios+=$paraPremiosCupon;
        }
        
        $totales[0]->setTotalCobroLocales($sumaCobroLocales);
        $totales[0]->setTotalGanancia($sumaGanancia);
        $totales[0]->setTotalParaPremios($sumaParaPremios);
        $em->persist($totales[0]);
        $em->flush();
    }
    
    function getSaldoParaPremios(){
        $totales = $this->findAll();
        $saldo = $totales[0]->getTotalParaPremios()-$totales[0]->getTotalGastadoPremios();
        return round($saldo, 2);
    }
}
