<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioMovilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioMovilRepository extends EntityRepository
{
    public function existUsaurioMovil($id){
        if($this->find($id) != null)
            return true;
        return false;
    }
}
