<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisitaLocalComercialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitaLocalComercialRepository extends EntityRepository {

    public function getVisitas() {
        $visitas = $this->getEntityManager()
                ->createQuery('SELECT l.id, l.nombre, count(v.id) as cant FROM AppBundle:VisitaLocalComercial v '
                        . ' JOIN v.localComercial l '
                        . ' GROUP BY l.id, l.nombre ')
                ->getResult();
        return $visitas;
    }

}
